// Generates the inline placeholders that keep every image box filled from the
// first paint. Run by `npm run lqip`, which `npm run build` runs first.
//
// The output is committed source (src/data/lqip.ts) rather than a build-time
// import, so the placeholders are in the bundle the moment React renders and
// cannot themselves become a request that has to finish.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import sharp from 'sharp'

const ROOT = path.resolve(import.meta.dirname, '..')
const PUBLIC_DIR = path.join(ROOT, 'public')
const OUT_FILE = path.join(ROOT, 'src', 'data', 'lqip.ts')

/** Directories whose images get a placeholder, relative to public/. */
const SCAN = ['images/capabilities', 'images/hands', 'clips']

/** Anything bigger stops being a hint and starts being a download. */
const LQIP_WIDTH = 20
const LQIP_QUALITY = 40

const SOURCE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.webp'])

async function collectSources() {
  const found = []
  for (const dir of SCAN) {
    const absolute = path.join(PUBLIC_DIR, dir)
    let entries
    try {
      entries = await readdir(absolute, { withFileTypes: true })
    } catch {
      continue
    }
    for (const entry of entries) {
      if (!entry.isFile()) continue
      if (!SOURCE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) continue
      found.push({
        // The key is the URL the browser asks for, so components can look a
        // placeholder up by the exact same string they put in `src`.
        key: `/${dir}/${entry.name}`,
        file: path.join(absolute, entry.name),
      })
    }
  }
  return found.sort((a, b) => a.key.localeCompare(b.key))
}

async function toLqip(file) {
  // `readFile` first, because some of these are re-encoded in place and sharp
  // should read bytes rather than trust the extension.
  const input = await readFile(file)
  const buffer = await sharp(input)
    .resize({ width: LQIP_WIDTH, withoutEnlargement: true })
    .blur(1.4)
    .webp({ quality: LQIP_QUALITY, alphaQuality: 60 })
    .toBuffer()
  return `data:image/webp;base64,${buffer.toString('base64')}`
}

const sources = await collectSources()
if (sources.length === 0) {
  console.error('gen-lqip: no source images found under public/ — refusing to write an empty map')
  process.exit(1)
}

const entries = []
for (const source of sources) {
  try {
    entries.push([source.key, await toLqip(source.file)])
  } catch (error) {
    console.error(`gen-lqip: failed on ${source.key}: ${error.message}`)
    process.exit(1)
  }
}

const body = entries.map(([key, uri]) => `  '${key}': '${uri}',`).join('\n')
const totalBytes = entries.reduce((sum, [, uri]) => sum + uri.length, 0)

const file = `// GENERATED by scripts/gen-lqip.mjs — do not edit by hand.
// Run \`npm run lqip\` after changing anything in public/images or public/clips.
//
// Each value is a ${LQIP_WIDTH}px-wide blurred WebP, inlined so it is painted from the
// bundle rather than fetched. They exist so that no image box is ever empty:
// the placeholder is in place at first paint and the real file cross-fades over
// it once decoded.

export const LQIP: Readonly<Record<string, string>> = {
${body}
}

/** Looks a placeholder up by the same URL a component passes to \`src\`. */
export function lqipFor(src: string): string | undefined {
  return LQIP[src]
}
`

await writeFile(OUT_FILE, file, 'utf8')
console.log(
  `gen-lqip: wrote ${entries.length} placeholders to src/data/lqip.ts (${(totalBytes / 1024).toFixed(1)} KB inline)`,
)
for (const [key, uri] of entries) {
  console.log(`  ${key.padEnd(42)} ${(uri.length / 1024).toFixed(2)} KB`)
}
